# Generated by Django 6.0.3 on 2026-04-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_first_app', '0002_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Дата и время дедлайна', null=True),
        ),
    ]
