# Generated by Django 6.0.3 on 2026-05-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_first_app', '0005_alter_category_deleted_at_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='my_first_app_customuser',
        ),
    ]
